name: flutter_eg990_mobile
description: EG990 mobile app for multi platforms.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=2.8.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  meta: ^1.2.4

  # Object Injectors https://pub.dev/packages/get_it
  get_it: ^5.0.3
  # A wrapper around InheritedWidget to make them easier to use and more reusable. https://pub.dev/packages/provider
  provider: ^4.3.2+3
  # Powerful Provider
#  flutter_riverpod: ^0.12.1
  # Functional programming thingies https://pub.dev/packages/dartz
  dartz: ^0.9.2
  # Stream Control Improve
  rxdart: ^0.25.0
  # MobX https://pub.dev/packages/mobx
  mobx: ^1.2.1+4
  flutter_mobx: ^1.1.0+2
  # Debug Logger https://pub.dev/packages/logger
  logging: ^0.11.4
  # App info
  package_info: ^0.4.3+2
  # Device info
  device_info: ^1.0.0
  # App settings launcher https://pub.dev/packages/app_settings
#  app_settings: ^4.0.4
  # UUID
  uuid: ^2.2.2

  # Network Service
  # HTTP Request - Dio https://pub.dev/packages/dio
  json_annotation: ^3.1.1
  dio: ^3.0.10
  dio_flutter_transformer: ^3.0.2
  # Cookie Manager https://pub.dev/packages/dio_cookie_manager
  dio_cookie_manager: ^1.0.0
  cookie_jar: ^1.0.1
  # HTTP Logger https://pub.dev/packages/pretty_dio_logger
  pretty_dio_logger: ^1.1.1
  # Network state
  connectivity: ^2.0.2
  data_connection_checker: ^0.3.4
  # JWT
  jwt_decoder: ^1.0.3


  # Data
  # Hive (noSQL) https://pub.dev/packages/hive
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  # Get commonly used locations on the filesystem. Supports iOS and Android.
  # https://pub.dev/packages/path_provider
  path_provider: ^1.6.24
  # Freezed (Data class with Json factory, Combine: super_enum, equatable, to_string,...) https://pub.dev/packages/freezed
  freezed_annotation: ^0.12.0
  # Simpler Data class(equatable, to_string, copyWith, hash) https://pub.dev/packages/dataclass
  #  dataclass: ^0.5.0+1
  # Super Enum (Enum with dynamic data) https://pub.dev/packages/super_enum
  super_enum: ^0.5.0
  # Enum class with constant data https://pub.dev/packages/vnum
  vnum: ^1.2.6
  # Validate Form https://pub.dev/packages/formz:
  formz: ^0.3.2

  # Device Related
  # Handle device permission https://pub.dev/packages/permission_handler
  permission_handler: ^5.0.1+1
  # Device Orientation https://pub.dev/packages/orientation
  orientation: ^1.2.0
  # Sensor Plugin https://pub.dev/packages/aeyrium_sensor
  # platform specific orientation code example
  #  aeyrium_sensor: ^1.0.7

  # UI
  # Navigator https://pub.dev/packages/auto_route
  auto_route: ^0.6.9
  # Toast https://pub.dev/packages/bot_toast
  bot_toast: ^3.0.5
  # Font Awesome from https://pub.dev/packages/font_awesome_flutter
  font_awesome_flutter: ^8.11.0
  # Layout Build Complete Mixin https://pub.dev/packages/after_layout
  after_layout: ^1.0.7+2
  # Official image extension https://pub.dev/packages/extended_image
  extended_image: ^1.5.0
  # Advance Photo Viewer https://pub.dev/packages/carousel_pro
  carousel_pro: ^1.0.0
  # Scroller Load & Refresh https://pub.dev/packages/flutter_easyrefresh
#  flutter_easyrefresh: ^2.1.6
  # Auto Resize Text
  auto_size_text: ^2.1.0
  # WebView https://pub.dev/packages/webview_flutter
  #  webview_flutter: ^1.0.7
  # Powerful Webview https://pub.dev/packages/flutter_inappwebview
  flutter_inappwebview: ^4.0.0+4
  # HTML as Widget https://pub.dev/packages/flutter_widget_from_html_core
  flutter_widget_from_html_core: ^0.5.1+4
  # QR Code generator https://pub.dev/packages/qr_flutter
  qr_flutter: ^3.2.0
  # General setting page widgets https://github.com/yako-dev/flutter-settings-ui
#  settings_ui: ^0.4.0
  # Configurable Expansion List Tile https://pub.dev/packages/configurable_expansion_tile
#  configurable_expansion_tile: ^1.0.0
  # Official Video Player https://pub.dev/packages/video_player/example
  video_player: ^1.0.1
  # dot border
#  dotted_border: ^1.0.7
  # custom round corner border
  custom_rounded_rectangle_border: ^0.0.1
  # Relative layout
  relative_layout: ^0.1.0+1


  # Utils
  # Localization & Datetime format
  intl: ^0.16.1
  # Email Validate https://pub.dev/packages/email_validator
  email_validator: ^1.0.6
  # Launch Url https://pub.dev/packages/url_launcher
  url_launcher: ^5.7.10
  # Share Function https://pub.dev/packages/share_extend
  share_extend: ^1.1.9

  # Firebase analytics
  #  firebase_core: ^0.5.2
  #  firebase_analytics: ^6.2.0
  #  firebase_auth: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0
  mockito: ^4.1.3
  reflectable: ^2.2.9
  hive_generator: ^0.8.2
  mobx_codegen: ^1.1.2
  json_serializable: ^3.5.1
  freezed: ^0.12.6
  #  dataclass_generator: ^0.5.0+2
  auto_route_generator: ^0.6.10
  source_gen: any
  build_runner: any

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - config/app_config.json
    - assets/images/
    - assets/images/icon/
    - assets/images/badges/
    - assets/images/nav/
    - assets/images/features/
    - assets/images/deposit/
    - assets/images/deposit/help/
    - assets/images/home/
    - assets/images/home/platforms/
    - assets/images/home/categories/
    - assets/images/about/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  # FontAwesome https://fontawesome.com/
  # Example: Icon(IconData(0xf834, fontFamily: 'FontAwesome'))
  fonts:
    - family: FontAwesome
      fonts:
        - asset: assets/fonts/fontawesome_webfont.ttf
          weight: 400
    - family: IconMoon
      fonts:
        - asset: assets/fonts/icomoon.ttf
          weight: 400


# Flutter localization tool
flutter_intl:
  enabled: true
