enum MainScreenAppBarTypes {
  LOGO_AND_MESSAGE_CENTER,
  TITLE_ONLY,
  TITLE_AND_SETTINGS,
  BACK_AND_TITLE,
  BACK_TITLE_SEARCH,
  BACK_TITLE_TUTORIAL,
}

enum MainScreenNavBarTypes {
  HOME,
  HIDE,
}
