/// Generated by AssetsRefGenerator on 2020/11/21
class Res {
  static const String fontawesome_webfont =
      "assets/fonts/fontawesome_webfont.ttf";
  static const String icomoon = "assets/fonts/icomoon.ttf";
  static const String badge_daily = "assets/images/badges/badge_daily.png";
  static const String badge_limit = "assets/images/badges/badge_limit.png";
  static const String badge_new_member =
      "assets/images/badges/badge_new_member.png";
  static const String f_icon_account =
      "assets/images/features/f_icon_account.png";
  static const String f_icon_bets = "assets/images/features/f_icon_bets.png";
  static const String f_icon_deposit =
      "assets/images/features/f_icon_deposit.png";
  static const String f_icon_store = "assets/images/features/f_icon_store.png";
  static const String f_icon_transfer =
      "assets/images/features/f_icon_transfer.png";
  static const String f_icon_transfer_record =
      "assets/images/features/f_icon_transfer_record.png";
  static const String f_icon_vip = "assets/images/features/f_icon_vip.png";
  static const String f_icon_vip_about =
      "assets/images/features/f_icon_vip_about.png";
  static const String f_icon_wallet =
      "assets/images/features/f_icon_wallet.png";
  static const String f_icon_withdraw =
      "assets/images/features/f_icon_withdraw.png";
  static const String img_no_card = "assets/images/features/img_no_card.png";
  static const String img_no_data = "assets/images/features/img_no_data.png";
  static const String img_no_data_2 =
      "assets/images/features/img_no_data_2.png";
  static const String img_no_exchange_data =
      "assets/images/features/img_no_exchange_data.png";
  static const String wallet_crown = "assets/images/features/wallet_crown.png";
  static const String wallet_gifts = "assets/images/features/wallet_gifts.png";
  static const String wallet_growth =
      "assets/images/features/wallet_growth.png";
  static const String wallet_task = "assets/images/features/wallet_task.png";
  static const String menu_card = "assets/images/home/categories/menu_card.png";
  static const String menu_card_u =
      "assets/images/home/categories/menu_card_u.png";
  static const String menu_esport =
      "assets/images/home/categories/menu_esport.png";
  static const String menu_esport_u =
      "assets/images/home/categories/menu_esport_u.png";
  static const String menu_live = "assets/images/home/categories/menu_live.png";
  static const String menu_live_u =
      "assets/images/home/categories/menu_live_u.png";
  static const String menu_lottery =
      "assets/images/home/categories/menu_lottery.png";
  static const String menu_lottery_u =
      "assets/images/home/categories/menu_lottery_u.png";
  static const String menu_slot = "assets/images/home/categories/menu_slot.png";
  static const String menu_slot_u =
      "assets/images/home/categories/menu_slot_u.png";
  static const String menu_sport =
      "assets/images/home/categories/menu_sport.png";
  static const String menu_sport_u =
      "assets/images/home/categories/menu_sport_u.png";
  static const String sport_app = "assets/images/home/categories/sport_app.png";
  static const String sport_app_u =
      "assets/images/home/categories/sport_app_u.png";
  static const String yabo_card = "assets/images/home/categories/yabo_card.png";
  static const String yabo_card_u =
      "assets/images/home/categories/yabo_card_u.png";
  static const String marquee_hot_game =
      "assets/images/home/marquee_hot_game.png";
  static const String marquee_loudly = "assets/images/home/marquee_loudly.png";
  static const String mob_card_kd =
      "assets/images/home/platforms/mob_card_kd.png";
  static const String mob_card_sw =
      "assets/images/home/platforms/mob_card_sw.png";
  static const String mob_card_ww =
      "assets/images/home/platforms/mob_card_ww.png";
  static const String mob_esports_ig =
      "assets/images/home/platforms/mob_esports_ig.png";
  static const String mob_esports_im =
      "assets/images/home/platforms/mob_esports_im.png";
  static const String mob_fish = "assets/images/home/platforms/mob_fish.png";
  static const String mob_live_ag =
      "assets/images/home/platforms/mob_live_ag.png";
  static const String mob_live_bb =
      "assets/images/home/platforms/mob_live_bb.png";
  static const String mob_live_bg =
      "assets/images/home/platforms/mob_live_bg.png";
  static const String mob_live_ebet =
      "assets/images/home/platforms/mob_live_ebet.jpg";
  static const String mob_live_og =
      "assets/images/home/platforms/mob_live_og.png";
  static const String mob_live_yabo =
      "assets/images/home/platforms/mob_live_yabo.png";
  static const String mob_lottery_bbin =
      "assets/images/home/platforms/mob_lottery_bbin.png";
  static const String mob_lottery_lb =
      "assets/images/home/platforms/mob_lottery_lb.png";
  static const String mob_lottery_tcg =
      "assets/images/home/platforms/mob_lottery_tcg.png";
  static const String mob_lottery_yabo =
      "assets/images/home/platforms/mob_lottery_yabo.png";
  static const String mob_slot_dt =
      "assets/images/home/platforms/mob_slot_dt.png";
  static const String mob_slot_mg =
      "assets/images/home/platforms/mob_slot_mg.png";
  static const String mob_slot_pg =
      "assets/images/home/platforms/mob_slot_pg.png";
  static const String mob_slot_pp =
      "assets/images/home/platforms/mob_slot_pp.png";
  static const String mob_slot_pt =
      "assets/images/home/platforms/mob_slot_pt.png";
  static const String mob_sport_im =
      "assets/images/home/platforms/mob_sport_im.png";
  static const String mob_sport_yabo =
      "assets/images/home/platforms/mob_sport_yabo.png";
  static const String tab_bg_normal = "assets/images/home/tab_bg_normal.png";
  static const String tab_bg_selected =
      "assets/images/home/tab_bg_selected.png";
  static const String entry_checkbox_false_icon =
      "assets/images/icon/entry_checkbox_false_icon.png";
  static const String entry_checkbox_true_icon =
      "assets/images/icon/entry_checkbox_true_icon.png";
  static const String entry_clear_icon =
      "assets/images/icon/entry_clear_icon.png";
  static const String entry_hide_password =
      "assets/images/icon/entry_hide_password.png";
  static const String entry_password_icon =
      "assets/images/icon/entry_password_icon.png";
  static const String entry_tips_icon =
      "assets/images/icon/entry_tips_icon.png";
  static const String entry_tips_icon_err =
      "assets/images/icon/entry_tips_icon_err.png";
  static const String entry_user_icon =
      "assets/images/icon/entry_user_icon.png";
  static const String entry_verify_icon =
      "assets/images/icon/entry_verify_icon.png";
  static const String hot_game_refresh =
      "assets/images/icon/hot_game_refresh.png";
  static const String icon_close = "assets/images/icon/icon_close.png";
  static const String icon_close_round =
      "assets/images/icon/icon_close_round.png";
  static const String icon_point_at = "assets/images/icon/icon_point_at.png";
  static const String icon_question = "assets/images/icon/icon_question.png";
  static const String img_tip = "assets/images/icon/img_tip.png";
  static const String refresh_1 = "assets/images/icon/refresh_1.png";
  static const String refresh_2 = "assets/images/icon/refresh_2.png";
  static const String icon_bar_logo = "assets/images/icon_bar_logo.png";
  static const String icon_about = "assets/images/nav/icon_about.png";
  static const String icon_app = "assets/images/nav/icon_app.png";
  static const String icon_bonus = "assets/images/nav/icon_bonus.png";
  static const String icon_bonus_u = "assets/images/nav/icon_bonus_u.png";
  static const String icon_export = "assets/images/nav/icon_export.png";
  static const String icon_help = "assets/images/nav/icon_help.png";
  static const String icon_home = "assets/images/nav/icon_home.png";
  static const String icon_home_u = "assets/images/nav/icon_home_u.png";
  static const String icon_invite = "assets/images/nav/icon_invite.png";
  static const String icon_join = "assets/images/nav/icon_join.png";
  static const String icon_record = "assets/images/nav/icon_record.png";
  static const String icon_service = "assets/images/nav/icon_service.png";
  static const String icon_service_u = "assets/images/nav/icon_service_u.png";
  static const String icon_sponsor = "assets/images/nav/icon_sponsor.png";
  static const String icon_sponsor_u = "assets/images/nav/icon_sponsor_u.png";
  static const String icon_time = "assets/images/nav/icon_time.png";
  static const String icon_user = "assets/images/nav/icon_user.png";
  static const String icon_user_u = "assets/images/nav/icon_user_u.png";
}
