/// Generated by AssetsRefGenerator on 2020/07/31
class Res {
  //  static const String fontawesome_webfont = "assets/fonts/fontawesome_webfont.ttf";
  static const String wallpaper = "";
//  static const String shadow = "assets/images/shadow.png";
  static const String homeBoxUserAreaBg = "";
  static const String iconBarLogo = "assets/images/icon_bar_logo.png";
  static const String iconPending = "assets/images/icon_pending.png";
  static const String iconLine = "assets/images/icon_line.png";

//  static const String tbico_casino = "assets/images/index/tbico_casino.png";
//  static const String tbico_slot = "assets/images/index/tbico_slot.png";
//  static const String tbico_sport = "assets/images/index/tbico_sport.png";
//  static const String tbico_fish = "assets/images/index/tbico_fish.png";
//  static const String tbico_lottery = "assets/images/index/tbico_lottery.png";
//  static const String tbico_card = "assets/images/index/tbico_card.png";
//  static const String tbico_movie = "assets/images/index/tbico_movie.png";
//  static const String tbico_recommend =
//      "assets/images/index/tbico_recommend.png";
//  static const String tbico_love = "assets/images/index/tbico_love.png";
  static const String tbico_fav = "assets/images/index/tbico_love_dark.png";

  static const String flico_word = "assets/images/flico_word.png";

  static const String walletBgIcon = "assets/images/wlpop_titico.png";
  static const String walletBgIconSmall =
      "assets/images/wlpop_titico_small.png";

  static const String homeMemberAreaIconDeposit =
      "assets/images/icons/idxusico_dsp.png";
  static const String homeMemberAreaIconWithdraw =
      "assets/images/icons/idxusico_cash.png";
  static const String homeMemberAreaIconTransfer =
      "assets/images/icons/idxusico_tsf.png";
  static const String homeMemberAreaIconVip =
      "assets/images/icons/idxusico_vip.png";
  static const String homeMemberAreaIconOther =
      "assets/images/icons/icon_other.png";
}
